### ISSUE TITLE
Grafikbug: fehlende spalten in Sprites

### ISSUE THREAD

**Issue by Schorschae** [Tivorak/SideScroller#2]
An bestimmten positionen verschwinden verschiedene 1 pixel breite spalten aus den sprites.
Zb Spalte in der Gendalfs Auge (zumindest die Pupille) ist, verschwindet wenn man genau am rechten rand der Platform steht (wenn sich die weissen kollisionsboxenränder überschneiden)

**Comment by Tivorak** [comment]
Problem bei Grafik mit niedriger Auflösung
